name: Build and Test Library

on:
  push:

jobs:
  test-library:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "^1.21"
        
    - name: Test
      run: COINPAYMENTS_PUBLIC_KEY="${{secrets.COINPAYMENTS_PUBLIC_KEY}}" COINPAYMENTS_PRIVATE_KEY="${{secrets.COINPAYMENTS_PRIVATE_KEY}}" go test -v ./...
